apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow.fullname" . }}-scheduler
  labels:
    {{- include "airflow.global.labels" . | nindent 4 }}
    {{- include "airflow.scheduler.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    # Kill the scheduler as soon as possible. It will restart quickly with all the workers,
    # minimizing the time they are not synchronized.
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  selector:
    matchLabels:
      {{- include "airflow.global.selectorLabels" . | nindent 6 }}
      {{- include "airflow.scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airflow.global.selectorLabels" . | nindent 8 }}
        {{- include "airflow.scheduler.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "airflow.scheduler.serviceAccountName" . }}
      restartPolicy: Always
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      # initContainers:
      #   - name: run-airflow-migrations
      #     image: "{{ .Values.images.airflow.repository }}:{{ .Values.images.airflow.tag }}"
      #     imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
      #     args:
      #       - airflow
      #       - upgradedb
      containers:
        - name: scheduler
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.airflow.repository }}:{{ .Values.images.airflow.tag }}"
          imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
          args:
            - airflow
            - scheduler
          resources:
            {{- toYaml .Values.resources.scheduler | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "airflow.fullname" . }}
            - configMapRef:
                name: {{ include "airflow.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
